# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SEI CERT C++ Coding Stardard中文翻译
email: unice2345@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  本内容是SEI CERT C++ Coding Stardard的中文翻译。并非官方版本，只是个人翻译。
  内容并不完整，并有可能有不准确的地方。
  SEI CERT C++ Coding Stardard是一项C++语言的安全编码规范。其中列举了一些C++编程中
  应遵守的安全编程规范，并阐述原因和列举了代码示例，对C++编程人员是很好的学习指导。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  unice2345

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
